### ISSUE TITLE
spacing

### ISSUE THREAD

**Issue by erickabsmith** [erickabsmith/masters-project-lcz-classification#7]
Try to make references section and Table 1 single spaced

**Comment by cwickham** [comment]
You can wrap the parts you want single space in `\begin{singlespace}` and `\end{singlespace}`, e.g. for table 1:
````
\begin{singlespace}
```{r echo=FALSE}
scene_dat[,2:3] %>%
kable(caption = "Acquisition Dates of Each Landsat 8 Scene", format='latex',linesep='',booktabs=TRUE,escape=FALSE) %>%
  kable_styling(latex_options = c('striped','HOLD_position'), font_size = 8)
```
\end{singlespace}

````

Oh, and the page limit problem may be worse than anticipated.  The guidebook says 12pt font!  So, you'll need to add:
```
fontsize: 12pt
```
to the header.  This currently results in 20 pages!
